public class FirstWritingTask2 {
    /*

    (W) a) Why does an arrival event need to generate a new arrival event? b) Which event should be generated by the start of the service?

    a)
    Jatkuvat saapumiset varmistetaan sillä, että luodaan uusi saapumistapahtuma toisen jälkeen dynaamisesti.
    Oikeassa elämässä saapumiset eivät tapahdu kaikki kerralla ja simulaatiossa saapuminen käynnistää ajastuksen toiseen saapumiseen.

    b)

    Alussa pitää määrittää päättymistapahtuma, milloin simulaatio keskeytetään ja ensimmäinen saapuminen, jonka jälkeen simulaatio lähtee käyntiin.



     */
}
